version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    build:
       context: .
       dockerfile: containers/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./containers/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/pong:/var/www/game/
    restart: on-failure
    networks:
      - transcendence
  database:
    container_name: postgres
    # build:
    #    context: .
    #    dockerfile: containers/postgres/Dockerfile
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database_vol:/var/lib/postgresql/data
    env_file: .env
    networks:
      - transcendence
  django:
    image: django:latest
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    command: python3 containers/django/tr_test/manage.py runserver 0.0.0.0:8000
    container_name: django
    volumes:
      - .:/work_dir
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - DB_HOST=${DB_HOST}
    env_file: .env
    depends_on:
      - database
    networks:
      - transcendence
volumes:
  database_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/smunio/tr_vol/database'
networks:
  transcendence:
    driver: bridge